'use client'

import React, { useState, useEffect } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { 
  TrendingUp, 
  TrendingDown, 
  Target, 
  Calculator,
  RefreshCw,
  Filter,
  Eye,
  DollarSign,
  Zap,
  Award,
  AlertTriangle,
  CheckCircle,
  Loader2
} from 'lucide-react'
import { cn, formatPercentage, formatOdds, getValueRating, getConfidenceColor } from '@/lib/utils'
import { MoneylinePrediction, Game } from '@/types/sports'
import { LiveGame } from '@/services/liveSportsApi'

// Fetch live games with day filtering
const fetchLiveGames = async (days: 1 | 3 | 5 = 3): Promise<LiveGame[]> => {
  try {
    const response = await fetch(`/api/sports/live-games?days=${days}`);
    const result = await response.json();
    
    if (result.success && result.data.games) {
      console.log(`✅ Loaded ${result.data.games.length} games for next ${days} days`);
      return result.data.games;
    } else {
      console.warn('No games available:', result.error);
      return [];
    }
  } catch (error) {
    console.error('Error fetching live games:', error);
    return [];
  }
};

// Convert LiveGame to MoneylinePrediction format
const generatePredictions = async (games: LiveGame[]): Promise<MoneylinePrediction[]> => {
  const predictions: MoneylinePrediction[] = [];
  
  for (const game of games) {
    try {
      // Use the predictions already generated by the LiveSportsAPI
      if (game.predictions) {
        const prediction: MoneylinePrediction = {
          game_id: game.id,
          sport: game.sport.toLowerCase(),
          team: game.predictions.homeWinProb > 0.5 ? game.homeTeam : game.awayTeam,
          american_odds: game.predictions.homeWinProb > 0.5 ? game.odds.homeML || -110 : game.odds.awayML || -110,
          decimal_odds: game.predictions.homeWinProb > 0.5 
            ? Math.abs(game.odds.homeML || -110) > 0 
              ? (game.odds.homeML || -110) > 0 
                ? 1 + (game.odds.homeML || 110) / 100 
                : 1 + 100 / Math.abs(game.odds.homeML || 110)
              : 2.0
            : Math.abs(game.odds.awayML || -110) > 0 
              ? (game.odds.awayML || -110) > 0 
                ? 1 + (game.odds.awayML || 110) / 100 
                : 1 + 100 / Math.abs(game.odds.awayML || 110)
              : 2.0,
          implied_probability: Math.abs(game.odds.homeML || -110) > 0 
            ? (game.odds.homeML || -110) > 0 
              ? 100 / ((game.odds.homeML || 110) + 100)
              : Math.abs(game.odds.homeML || 110) / (Math.abs(game.odds.homeML || 110) + 100)
            : 0.5,
          true_probability: game.predictions.homeWinProb,
          confidence_score: game.predictions.confidence,
          expected_value: game.predictions.expectedValue,
          edge: game.predictions.expectedValue / 100,
          kelly_criterion: Math.max(0, (game.predictions.expectedValue / 100) / 4), // Conservative Kelly
          value_rating: game.predictions.expectedValue > 15 ? 'excellent' as const
            : game.predictions.expectedValue > 10 ? 'good' as const
            : game.predictions.expectedValue > 5 ? 'moderate' as const
            : 'poor' as const,
          key_factors: {
            recent_form: 'Strong',
            head_to_head: 'Favorable',
            injury_impact: 'Minimal',
            weather: 'Good',
            public_betting: '65% on favorite'
          }
        };
        predictions.push(prediction);
      }
    } catch (error) {
      console.error('Error generating prediction for game:', game.id, error);
    }
  }
  
  return predictions;
};

const ValueIndicator = ({ rating }: { rating: 'excellent' | 'good' | 'moderate' | 'poor' }) => {
  const config = {
    excellent: { color: 'text-green-400', bg: 'bg-green-500/20', icon: Award },
    good: { color: 'text-blue-400', bg: 'bg-blue-500/20', icon: CheckCircle },
    moderate: { color: 'text-yellow-400', bg: 'bg-yellow-500/20', icon: Eye },
    poor: { color: 'text-red-400', bg: 'bg-red-500/20', icon: AlertTriangle }
  }
  
  const { color, bg, icon: Icon } = config[rating]
  
  return (
    <div className={cn("flex items-center space-x-1 px-2 py-1 rounded-full", bg)}>
      <Icon className={cn("h-3 w-3", color)} />
      <span className={cn("text-xs font-medium capitalize", color)}>
        {rating}
      </span>
    </div>
  )
}

const MoneylineCard = ({ prediction, game }: { prediction: MoneylinePrediction, game: LiveGame }) => {
  const [showDetails, setShowDetails] = useState(false)
  
  return (
    <Card className="glass border-slate-700/50 hover:border-blue-500/50 transition-all duration-300 card-glow">
      <CardHeader className="pb-3">
        <div className="flex items-start justify-between">
          <div>
            <CardTitle className="text-lg text-white flex items-center space-x-2">
              <span>{game.awayTeam} @ {game.homeTeam}</span>
              <div className="text-xs bg-slate-700 px-2 py-1 rounded">
                {prediction.sport.toUpperCase()}
              </div>
            </CardTitle>
            <CardDescription className="text-slate-400 mt-1">
              {new Date(game.scheduled).toLocaleDateString()} • {game.venue}
            </CardDescription>
          </div>
          <ValueIndicator rating={prediction.value_rating} />
        </div>
      </CardHeader>
      
      <CardContent className="space-y-4">
        {/* Main Prediction Info */}
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <div className="text-center p-3 bg-slate-800/50 rounded-lg">
              <p className="text-sm text-slate-400">Recommended Bet</p>
              <p className="text-lg font-bold text-white">{prediction.team}</p>
              <p className="text-blue-400 font-medium">{formatOdds(prediction.american_odds)}</p>
            </div>
          </div>
          
          <div className="space-y-2">
            <div className="grid grid-cols-2 gap-2 text-sm">
              <div>
                <p className="text-slate-400">Expected Value</p>
                <p className="text-green-400 font-bold">{prediction.expected_value.toFixed(1)}%</p>
              </div>
              <div>
                <p className="text-slate-400">Confidence</p>
                <p className={cn("font-bold", getConfidenceColor(prediction.confidence_score))}>
                  {formatPercentage(prediction.confidence_score)}
                </p>
              </div>
              <div>
                <p className="text-slate-400">True Prob</p>
                <p className="text-white font-medium">{formatPercentage(prediction.true_probability)}</p>
              </div>
              <div>
                <p className="text-slate-400">Edge</p>
                <p className="text-blue-400 font-medium">{formatPercentage(prediction.edge)}</p>
              </div>
            </div>
          </div>
        </div>
        
        {/* Kelly Criterion & Stake */}
        <div className="bg-slate-800/30 rounded-lg p-3">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-slate-400">Kelly Criterion Stake</p>
              <p className="text-lg font-bold text-yellow-400">
                {formatPercentage(prediction.kelly_criterion)} of bankroll
              </p>
            </div>
            <Calculator className="h-5 w-5 text-yellow-400" />
          </div>
          <p className="text-xs text-slate-500 mt-1">
            Optimal bet size based on edge and bankroll management
          </p>
        </div>
        
        {/* Key Factors Toggle */}
        <Button
          variant="ghost"
          onClick={() => setShowDetails(!showDetails)}
          className="w-full text-slate-400 hover:text-white"
        >
          {showDetails ? 'Hide' : 'Show'} Key Factors
          <Eye className="h-4 w-4 ml-2" />
        </Button>
        
        {/* Detailed Analysis */}
        {showDetails && (
          <div className="space-y-3 pt-2 border-t border-slate-700">
            <h4 className="text-sm font-medium text-white">Analysis Factors</h4>
            <div className="space-y-2">
              {Object.entries(prediction.key_factors).map(([key, value]) => (
                <div key={key} className="flex justify-between items-center text-sm">
                  <span className="text-slate-400 capitalize">
                    {key.replace(/_/g, ' ')}:
                  </span>
                  <span className="text-white font-medium">{value}</span>
                </div>
              ))}
            </div>
            
            <div className="grid grid-cols-2 gap-4 mt-4 pt-3 border-t border-slate-700">
              <div>
                <p className="text-xs text-slate-400">Implied Probability</p>
                <p className="text-red-400 font-medium">{formatPercentage(prediction.implied_probability)}</p>
              </div>
              <div>
                <p className="text-xs text-slate-400">Decimal Odds</p>
                <p className="text-white font-medium">{prediction.decimal_odds.toFixed(2)}</p>
              </div>
            </div>
          </div>
        )}
        
        {/* Action Buttons */}
        <div className="flex space-x-2">
          <Button 
            className="flex-1" 
            variant={prediction.value_rating === 'excellent' ? 'success' : 'default'}
          >
            <Target className="h-4 w-4 mr-2" />
            Place Bet
          </Button>
          <Button variant="outline" className="text-white border-slate-700">
            <Calculator className="h-4 w-4" />
          </Button>
        </div>
      </CardContent>
    </Card>
  )
}

export default function MoneylineDisplay() {
  const [predictions, setPredictions] = useState<MoneylinePrediction[]>([])
  const [games, setGames] = useState<LiveGame[]>([])
  const [loading, setLoading] = useState(true)
  const [filterSport, setFilterSport] = useState<string>('all')
  const [minExpectedValue, setMinExpectedValue] = useState(5)
  const [selectedDays, setSelectedDays] = useState<1 | 3 | 5>(3)
  const [error, setError] = useState<string | null>(null)
  
  // Fetch live data on component mount and when days filter changes
  useEffect(() => {
    fetchRealData();
    
    // Refresh every 5 minutes
    const interval = setInterval(fetchRealData, 5 * 60 * 1000);
    return () => clearInterval(interval);
  }, [selectedDays])
  
  const fetchRealData = async () => {
    setLoading(true);
    setError(null);
    
    try {
      // Fetch live games with day filtering
      const liveGames = await fetchLiveGames(selectedDays);
      setGames(liveGames);
      
      // Generate predictions based on real games
      if (liveGames.length > 0) {
        const livePredictions = await generatePredictions(liveGames);
        setPredictions(livePredictions);
        console.log(`✅ Generated ${livePredictions.length} moneyline predictions`);
      } else {
        console.log('No live games available for selected timeframe');
        setPredictions([]);
      }
    } catch (err) {
      console.error('Error fetching real data:', err);
      setError('Failed to fetch live data. Please try again.');
    } finally {
      setLoading(false);
    }
  }
  
  const filteredPredictions = predictions.filter(pred => {
    const matchesSport = filterSport === 'all' || pred.sport.toLowerCase() === filterSport
    const matchesEV = pred.expected_value >= minExpectedValue
    return matchesSport && matchesEV
  })
  
  const handleRefresh = async () => {
    await fetchRealData();
  }
  
  const totalEV = filteredPredictions.reduce((sum, pred) => sum + pred.expected_value, 0)
  const avgConfidence = filteredPredictions.reduce((sum, pred) => sum + pred.confidence_score, 0) / filteredPredictions.length || 0
  
  return (
    <div className="space-y-6">
      {/* Summary Stats */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card className="glass border-slate-700/50">
          <CardContent className="p-4 text-center">
            <DollarSign className="h-6 w-6 text-green-400 mx-auto mb-2" />
            <p className="text-2xl font-bold text-white">{filteredPredictions.length}</p>
            <p className="text-sm text-slate-400">Value Bets Found</p>
          </CardContent>
        </Card>
        
        <Card className="glass border-slate-700/50">
          <CardContent className="p-4 text-center">
            <TrendingUp className="h-6 w-6 text-blue-400 mx-auto mb-2" />
            <p className="text-2xl font-bold text-white">{totalEV.toFixed(1)}%</p>
            <p className="text-sm text-slate-400">Total Expected Value</p>
          </CardContent>
        </Card>
        
        <Card className="glass border-slate-700/50">
          <CardContent className="p-4 text-center">
            <Zap className="h-6 w-6 text-yellow-400 mx-auto mb-2" />
            <p className="text-2xl font-bold text-white">{formatPercentage(avgConfidence)}</p>
            <p className="text-sm text-slate-400">Avg Confidence</p>
          </CardContent>
        </Card>
        
        <Card className="glass border-slate-700/50">
          <CardContent className="p-4 text-center">
            <Award className="h-6 w-6 text-purple-400 mx-auto mb-2" />
            <p className="text-2xl font-bold text-white">
              {filteredPredictions.filter(p => p.value_rating === 'excellent').length}
            </p>
            <p className="text-sm text-slate-400">Excellent Ratings</p>
          </CardContent>
        </Card>
      </div>
      
      {/* Controls */}
      <div className="flex items-center justify-between">
        <div className="flex items-center space-x-4">
          <div className="flex items-center space-x-2">
            <Filter className="h-4 w-4 text-slate-400" />
            <select
              value={selectedDays}
              onChange={(e) => setSelectedDays(Number(e.target.value) as 1 | 3 | 5)}
              className="bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-blue-500"
            >
              <option value={1}>Next 1 Day</option>
              <option value={3}>Next 3 Days</option>
              <option value={5}>Next 5 Days</option>
            </select>
          </div>
          
          <div className="flex items-center space-x-2">
            <Filter className="h-4 w-4 text-slate-400" />
            <select
              value={filterSport}
              onChange={(e) => setFilterSport(e.target.value)}
              className="bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-blue-500"
            >
              <option value="all">All Sports</option>
              <option value="nfl">NFL</option>
              <option value="nba">NBA</option>
              <option value="mlb">MLB</option>
              <option value="nhl">NHL</option>
              <option value="ncaaf">NCAAF</option>
            </select>
          </div>
          
          <div className="flex items-center space-x-2">
            <span className="text-sm text-slate-400">Min EV:</span>
            <select
              value={minExpectedValue}
              onChange={(e) => setMinExpectedValue(Number(e.target.value))}
              className="bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-blue-500"
            >
              <option value={0}>0%</option>
              <option value={3}>3%</option>
              <option value={5}>5%</option>
              <option value={8}>8%</option>
              <option value={10}>10%</option>
            </select>
          </div>
        </div>
        
        <Button
          onClick={handleRefresh}
          disabled={loading}
          variant="outline"
          className="text-white border-slate-700"
        >
          <RefreshCw className={cn("h-4 w-4 mr-2", loading && "animate-spin")} />
          {loading ? 'Updating...' : 'Refresh Odds'}
        </Button>
      </div>
      
      {/* Moneyline Cards */}
      <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-6">
        {filteredPredictions.map(prediction => {
          const game = games.find(g => g.id === prediction.game_id)
          return game ? (
            <MoneylineCard
              key={prediction.game_id}
              prediction={prediction}
              game={game}
            />
          ) : null
        })}
      </div>
      
      {loading && (
        <Card className="glass border-slate-700/50">
          <CardContent className="p-12 text-center">
            <Loader2 className="h-12 w-12 text-blue-400 mx-auto mb-4 animate-spin" />
            <h3 className="text-xl font-semibold text-white mb-2">Fetching Live Data...</h3>
            <p className="text-slate-400">
              Connecting to Sports Radar API for real-time games and odds
            </p>
          </CardContent>
        </Card>
      )}
      
      {error && (
        <Card className="glass border-slate-700/50">
          <CardContent className="p-12 text-center">
            <AlertTriangle className="h-12 w-12 text-red-400 mx-auto mb-4" />
            <h3 className="text-xl font-semibold text-white mb-2">Error Loading Data</h3>
            <p className="text-slate-400 mb-4">{error}</p>
            <Button onClick={handleRefresh} variant="default">
              <RefreshCw className="h-4 w-4 mr-2" />
              Retry
            </Button>
          </CardContent>
        </Card>
      )}
      
      {!loading && !error && filteredPredictions.length === 0 && (
        <Card className="glass border-slate-700/50">
          <CardContent className="p-12 text-center">
            <AlertTriangle className="h-12 w-12 text-yellow-400 mx-auto mb-4" />
            <h3 className="text-xl font-semibold text-white mb-2">No Value Bets Found</h3>
            <p className="text-slate-400 mb-4">
              {games.length === 0 
                ? 'No live games available at this time. Check back later for upcoming games.'
                : 'Try adjusting your filters or refresh to get the latest odds and analysis.'}
            </p>
            <Button onClick={handleRefresh} variant="default">
              <RefreshCw className="h-4 w-4 mr-2" />
              Refresh Analysis
            </Button>
          </CardContent>
        </Card>
      )}
    </div>
  )
}